sudo: required
services:
  - docker

before_install:
  - docker build -t vladimirgruicic/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true vladimirgruicic/docker-react npm run test

deploy: 
  provider: elaticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-456582705970"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"